apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/target-namespace: koustav-demo
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: master
    pipelinesascode.tekton.dev/pipeline: ".tekton/pipeline-push-arm.yaml"
  generateName: pipelinerun-push-arm-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-push-arm
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: tag-name
      value: "{{ revision }}"
    - name: image-full-path-with-tag
      value: "quay.io/rh-ee-ksaha/test-arm-build:check"
  workspaces:
    - name: maven-settings
      configMap:
        name: maven-settings
    - name: workspace
      persistentVolumeClaim:
        claimName: shared-workspace
    - name: quay-cred
      secret:
        secretName: quay-secret
    - name: empty-dir
      emptyDir: {}
  
