apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/target-namespace: koustav-demo
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: master
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/koustavsaha/Tekton-pipeline-springboot/master/TektonPipelines/Pipeline/pipeline-push.yaml"
  generateName: pipelinerun-merge-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-push
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: tag-name
      value: "{{ revision }}"
    - name: image-full-path-with-tag
      value: "quay.io/rh-ee-ksaha/test:master"
    - name: deployment-manifest
      value: "https://raw.githubusercontent.com/koustavsaha/Tekton-pipeline-springboot/master/TektonPipelines/Resources/deployment.yaml"
  workspaces:
    - name: maven-settings
      configMap:
        name: maven-settings
    - name: workspace
      persistentVolumeClaim:
        claimName: shared-workspace
    - name: quay-cred
      secret:
        secretName: quay-secret
    - name: empty-dir
      emptyDir: {}
  